export default {
  startStation: null,
  endStation: null,
  departureDay: '',
  stations: [],
  routes: [],
  trainCars: [],
  seats: [],
  error: null,
  isLoadingTrainCar: false,
  isLoadingSeat: false,
  idTrainCar: null,
  idTrain: null,
  cart: [],
  objects: [],
  isSaved: false,
  isSaving: false,
  chosenSeats: [],
  countDowns: []
}
